apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-builder-privileged-role
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["privileged"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-builder-privileged-rolebinding
subjects:
  - kind: ServiceAccount
    name: pipeline
roleRef:
  kind: Role
  name: pipeline-builder-privileged-role
  apiGroup: rbac.authorization.k8s.io

