---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: fuse-demo-tekton-run-
spec:
  pipelineRef:
    name: spring-maven-pipeline
  resources:
  - name: fuse-demo-github
    resourceRef:
      name: fuse-demo-github-repo-openliberty
  - name: output-runnable-image
    resourceRef:
      name: fuse-demo-image
  params:
    - name: artifact_id
      value: "com.redhat:fuse-demo:1.0.0-SNAPSHOT"
    - name: nexus_url
      value: "nexus.apps.lab01.gpslab.club"
    - name: credentials
      value: "jenkins-nexus:redhat123"
    - name: deploymentNamespace
      value: "fuse-demo"
    - name: dockerfilePath
      value: "java-runner"
  workspaces:
  - name: spring-maven-repo
    persistentVolumeClaim:
      claimName: spring-maven-repo-pvc
