apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: postgres-backend
  kind: application
  master: argocd-application

resources:
  - project.yaml
  - postgres.yaml
