---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-backend
  namespace: openshift-gitops
spec:
  project: fuse-jdbc-demo
  source:
    repoURL: https://github.com/mcaimi/ocp4-tekton-demo.git
    targetRevision: main
    path: deployments/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
