apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fuse-jdbc-demo
commonLabels:
  app: signle-sign-on
  kind: operator
  master: argocd-application

resources:
  - operatorgroup.yaml
  - subscription.yaml
