bases:
  - ../common
namespace: fuse-demo
namePrefix: spring-
nameSuffix: "-github"
commonLabels:
  app: fuse-demo
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "noprod"
patchesStrategicMerge:
- ingress-route.yaml
- mem-sizing.yaml
secretGenerator:
- name: fuse-demo-init-secret
  literals:
  - postgres_app_user=fuse
  - postgres_app_db=fuse_db
  - postgres_app_user_password=fuse123
  - db_driver=postgresql
  - db_hostname=spring-postgres-service-github
  - db_port=5432
images:
- name: fuse-demo
  newName: image-registry.openshift-image-registry.svc:5000/fuse-demo/fuse-demo
  newTag: latest
