---
apiVersion: v1
kind: Secret
metadata:
  name: fuse-admin-secret
  namespace: fuse-jdbc-demo
type: Opaque
data:
  admin_password: cmVkaGF0MTIz
---
apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: fuse-jdbc-tenant
  namespace: fuse-jdbc-demo
spec:
  email: admin@fuse-spring.com
  masterCredentialsRef:
    name: system-seed
  organizationName: Fuse-Spring
  passwordCredentialsRef:
    name: fuse-admin-secret
  systemMasterUrl: 'https://master.apps.democluster.sandbox758.opentlc.com'
  tenantSecretRef:
    name: fuse-tenant-secret
    namespace: fuse-jdbc-demo
  username: fuseadmin
