---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: fuse-to-jdbc-product
  namespace: fuse-jdbc-demo
spec:
  providerAccountRef:
    name: fuse-tenant-secret
  name: Fuse to JDBC API
  description: Fuse to JDBC API Product
  systemName: fuse-product
  metrics:
    product_get_calls:
      friendlyName: "Product GET Calls"
      unit: "1"
    product_post_calls:
      friendlyName: "Product POST Calls"
      unit: "1"
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: "hit"
  methods:
    product_get_method:
      friendlyName: Fuse API GET Method Call
    product_post_method:
      friendlyName: Fuse API POST Method Call
  mappingRules:
    - httpMethod: GET
      pattern: "/api/get"
      increment: 1
      metricMethodRef: product_get_calls
    - httpMethod: POST
      pattern: "/api/post"
      increment: 1
      metricMethodRef: product_post_calls
  applicationPlans:
    fuseApiPlan:
      name: "Fuse to JDBC Rate Plan"
      trialPeriod: 1
      setupFee: "0.99"
      pricingRules:
        - from: 100
          to: 300
          pricePerUnit: "0.15"
          metricMethodRef:
            systemName: get_calls
            backend: fuse-backend
        - from: 100
          to: 300
          pricePerUnit: "0.15"
          metricMethodRef:
            systemName: post_calls
            backend: fuse-backend
      limits:
        - period: month
          value: 600
          metricMethodRef:
            systemName: post_calls
            backend: fuse-backend
        - period: week
          value: 150
          metricMethodRef:
            systemName: get_calls
            backend: fuse-backend
  backendUsages:
    fuse-backend:
      path: /
