apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: fuse-apimanager
  namespace: fuse-jdbc-demo
spec:
  wildcardDomain: apps.democluster.sandbox758.opentlc.com
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth-credentials
