apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: fuse-spring-app
  kind: application
  master: argocd-application

resources:
  - project.yaml
  - ci.yaml
  - deploy.yaml
