---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fuse-demo-servicemonitor
  namespace: jenkins
  labels:
    app: fuse-demo
spec:
  endpoints:
  - interval: 5s
    path: /q/metrics
    port: 80-tcp
    scheme: http
  selector:
    matchLabels:
      app: fuse-demo

