---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    name: tcp-postgres1
    protocol: TCP
    targetPort: 5432
  - port: 5433
    name: tcp-postgres2
    protocol: TCP
    targetPort: 5433
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP

